### PR TITLE
show all FileRecordTable rows until pagination implemented

### PR DESCRIPTION
**Pull request by ciaranschutte**
**Description of changes**

show all FileRecordTable rows until pagination implemented

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- [ ] Matches design:

  - component sizes, spacing, and styles
  - font size, weight, colour
  - spelling has been double checked

- [ ] New uikit components have Storybook stories
- [ ] Feature is minimally responsive.
- [ ] Manual testing of UI feature.
- [ ] Selenium test is completed and passing.

### CODE REVIEW

**Comment by wajiha-oicr** [comment]
cant you do showpagination = true or something like that?

**Comment by wajiha-oicr** [comment]
or are we waiting for server side pagination?

**Comment by rosibaj** [comment]
> @rosibaj are we waiting on server side pagination?

_backs away slowly from pagination details- 
 jkjk..

i think this should be ok for now, but correct me if im wrong here.  Post launch:
- need server side pagination from clinical
- need to update gateway to have pagination as well 
- need to update ui to read pagination. 

is this right?

**Comment by wajiha-oicr** [comment]
that sounds like a yes to me!

**Comment by ciaranschutte** [comment]
@hlminh2000 Changed to client side pagination :)

**Pull request merged**
