### PR TITLE
Feat/#779 file repo url bug

### PR DESCRIPTION
**Pull request by ciaranschutte**
**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

### CODE REVIEW

**Comment by rosibaj** [comment]
@joneubank @ciaranschutte is this PR still valid ?

**Comment by joneubank** [comment]
I'm not familiar with the ask here but the changes made look like they are probably needed - adding a return statement to a getInitialProps() request, and changing the path to data for workflowType.

Can we review the ticket it is meant for (#799 it looks like from the branch name) and see if that is still relevant?

Maybe @ciaranschutte knows more.

**Comment by ciaranschutte** [comment]
i will take a look @rosibaj

**Comment by ciaranschutte** [comment]
closing this to be migrated to a ticket. 

routing after logging in needs a query param, which is fine if the page you're trying to log into has no query params already
the issue with file repo is the file repo state is in the url too
so you get [File Repo State ] + [auth state] as query params, which our routing has no idea how to handle, resolving in a 404

this PR is stale, we need to take a look at our overall routing solution

**Pull request closed without merging**
