### PR TITLE
🔖 1.107.0 RC

### PR DESCRIPTION
**Pull request by mistryrn**
**Description of changes**

* Enables Small File Downloads on the File Entity page (#2091)
* Adds `RNASEQ` Feature Flag (#2217)
* Updates to the Team Page (#2113)
* Donor Entity page updates (#2127 #2126 #2242)
* Add File Name to File Entity Page https://github.com/icgc-argo/platform-ui/issues/2255

**Type of Change**

- [x] Bug
- [x] Styling
- [x] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [x] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [x] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [x] Feature is minimally responsive
- [x] Manual testing of UI feature
- [x] Add copyrights to new files
- [x] Connected ticket to PR

### CODE REVIEW

**Review by ciaranschutte — APPROVED** [review]
builds locally. looks good.

**Comment by ciaranschutte** [comment]
@mistryrn https://github.com/icgc-argo/platform-ui/pull/2256/files
this mergeback is still open just a heads up

**Comment by mistryrn** [comment]
> @mistryrn https://github.com/icgc-argo/platform-ui/pull/2256/files this mergeback is still open just a heads up

Yeah I had to resolve the merge conflict that has locally so I just included it as part of this RC, will close that one once this is in and open another after. Thanks for the heads up @ciaranschutte !

**Review by samrichca — APPROVED** [review]

**Comment by samrichca** [comment]
Added my field entity ticket to the description of this PR

**Pull request merged**
