### PR TITLE
🐛 puts back the missing scroll persistence

### PR DESCRIPTION
**Pull request by hlminh2000**
**Description of changes**

Just noticed this was removed, probably as a result of a bad conflict resolution.

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- [ ] Matches design:

  - component sizes, spacing, and styles
  - font size, weight, colour
  - spelling has been double checked

- [ ] New uikit components have Storybook stories
- [ ] Feature is minimally responsive.
- [ ] Manual testing of UI feature.
- [ ] Selenium test is completed and passing.

### CODE REVIEW

**Comment by hlminh2000** [comment]
@ciaranschutte what browser are you using? it seems ok for me on mac Chrome :/

**Comment by ciaranschutte** [comment]
> @ciaranschutte what browser are you using? it seems ok for me on mac Chrome :/

Ubuntu chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by hlminh2000** [comment]
let me try a quick fix for a test on your machine?

**Comment by ciaranschutte** [comment]
@rosibaj resolved #minhmagic

**Pull request merged**
