### PR TITLE
🐛 #2122 Vulnerable Dependency Updates

### PR DESCRIPTION
**Pull request by demariadaniel**
**Description of changes**

Updates libraries w/ critical dependency vulnerabilities
Adds npm-force-resolutions for libraries which require breaking updates (Storybook, Next.js)

**Type of Change**

- [x] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [x] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [x] No new UIKit components or changes
- [x] Feature is minimally responsive
- [x] Manual testing of UI feature
- [x] Add copyrights to new files
- [x] Connected ticket to PR

### CODE REVIEW

**Comment by ciaranschutte** [comment]
are these `ts-ignore`s due to difficulty typing them or not being able to type them?
even a rough "loose" type is better than ts-ignore I think, otherwise we slowly have a TS project where we tell it to ignore a tonne of stuff... before you know it we're only typing primitives `const x: string = 'end of times'`

**Comment by samrichca** [comment]
> are these `ts-ignore`s due to difficulty typing them or not being able to type them? even a rough "loose" type is better than ts-ignore I think, otherwise we slowly have a TS project where we tell it to ignore a tonne of stuff... before you know it we're only typing primitives `const x: string = 'end of times'`

agreed, should be able to type `schema` which seems to be the issue here

**Comment by demariadaniel** [comment]
> are these `ts-ignore`s due to difficulty typing them or not being able to type them? `

The `ts-ignore`'s were added because updating `yup` created Type errors which blocked pushing any commits
I'm reviewing the changes made by the Yup update and making updates
cc: @ciaranschutte  @samrichca

**Review by mistryrn — APPROVED** [review]
Assuming this is ready to go now since the builds are no longer broken 🙏

**Comment by demariadaniel** [comment]
> Assuming this is ready to go now since the builds are no longer broken 🙏

Yes! Runs on localhost & storybook builds & runs as well. Only remaining dependencies are linked to breaking changes

**Pull request merged**
